dist: trusty
os: linux
 
language: node_js
node_js:
  - lts/*

branches:
  only:
    - gitbook # 只监测 gitbook 分支上的 commit
 
cache:
  directories:
     - ./node_modules

before_install:
  - npm i -g gitbook-cli # 全局安装 gitbook-cli
  - sudo apt-get install calibre -y # 安装 calibre
  - sudo ln -s /usr/bin/nodejs /usr/bin/node # 建立软链接
 
install:
  - gitbook install # 安装 book.json 中的插件

# before_script:
  # - git submodule init # 更新子模块
  # - git submodule update

script:
  - gitbook build # 打包

after_script:
  - cd ./_book
  - git init
  - git config --global user.name "smpower"
  - git config --global user.email "rf.wangchn@gmail.com"
  - git add .
  - git commit -m "Updated gitbook by Travis-CI."
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master # 发布到 master 分支
  - gitbook pdf ./ ./supermemo-book.pdf # 生成 pdf 文档
  - gitbook epub ./ ./supermemo-book.epub # 生成 epub 文档
  - gitbook mobi ./ ./supermemo-book.mobi # 生成 mobi 文档

env:
  global:
    - GH_REF: github.com/smpower/supermemo.git
