dist: trusty
os: linux
 
language: node_js
node_js:
  - lts/*

branches:
  only:
    - gitbook # 只监测 gitbook 分支上的 commit
 
cache:
  directories:
     - ./node_modules

before_install:
  - npm i -g gitbook-cli # 全局安装 gitbook-cli
  - sudo apt-get install calibre -y # 安装 calibre
  - sudo ln -s /usr/bin/nodejs /usr/bin/node # 建立软链接

  # 解决下面生成 pdf 时报错的问题
  # 报错信息（非桌面环境报错）：RuntimeError: X server required. If you are running on a headless machine, use xvfb
  - sudo apt-get update && sudo apt-get install -y xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic xvfb x11-apps
  # 安装后依然报错，参考：
  # https://www.systutorials.com/241364/how-to-run-gitbook-on-a-headless-server-make-calibre-run-in-headless-server/
  # 的解决方法，创建 /usr/local/bin/ebook-convert 文件并赋予执行权限
  - sudo chmod +x ./ebook-convert
 
install:
  - gitbook install # 安装 book.json 中的插件

# before_script:
  # - git submodule init # 更新子模块
  # - git submodule update

script:
  - gitbook build # 打包

after_script:
  - cd ./_book
  - git init
  - git config --global user.name "smpower"
  - git config --global user.email "rf.wangchn@gmail.com"
  - git add .
  - git commit -m "Updated gitbook by Travis-CI."
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master # 发布到 master 分支
  - cd ../ && mkdir _book_file && cd _book_file
  - gitbook pdf ../_book/ ./supermemo.pdf # 生成 pdf 文档
  - gitbook epub ../_book/ ./supermemo.epub # 生成 epub 文档
  - gitbook mobi ../_book/ ./supermemo.mobi # 生成 mobi 文档
  - git init
  - git add .
  - git commit -m 'Generated book files.'
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:_book_file # 发布到 _book_file 分支

env:
  global:
    - GH_REF: github.com/smpower/supermemo.git
